import { defineIntegration, createRestHandler, fakeId, fakeArray, fakeEmail, fakeIsoTimestamp, deriveSeed } from '@weldable/integration-core'

const rest = createRestHandler()

export default defineIntegration({
  id: 'gmail',
  version: 1,
  name: 'Gmail',
  description: 'Read, search, and manage emails and labels via Gmail.',
  icon: 'gmail',
  exampleUsage: 'Check my inbox for anything urgent from this week',
  auth: {
    type: 'oauth2',
    test: async (_, ctx) => ctx.http.get('/users/me/profile').then(r => r.data as Record<string, unknown>),
  },
  baseUrl: 'https://gmail.googleapis.com/gmail/v1',
  nangoProvider: 'google-mail',
  nangoScopes: 'openid,email,https://mail.google.com/',
  nangoCredentialEnvPrefix: 'GOOGLE',
  actions: [
    // ── Messages ─────────────────────────────────────────────
    {
      actionId: 'list_messages',
      name: 'List messages',
      description: 'Browse recent emails in your inbox or a label.',
      intents: [
        'check my inbox',
        'see recent emails',
        'what emails do I have',
        'browse my inbox',
        'show my latest emails',
        'list my unread messages',
        'check my email',
      ],
      inputFields: [
        {
          name: 'q',
          type: 'string',
          required: false,
          description: 'Gmail search filter using Gmail search operators (https://developers.google.com/gmail/api/guides/filtering), e.g. "newer_than:1d", "is:unread", "from:someone@example.com", "subject:invoice has:attachment".',
        },
        {
          name: 'maxResults',
          type: 'number',
          required: false,
          description: 'Maximum number of messages to return.',
          default: 20,
        },
        {
          name: 'labelIds',
          type: 'string',
          required: false,
          description: 'Label to filter by, e.g. "INBOX" or "UNREAD".',
          default: 'INBOX',
        },
      ],
      outputFields: [
        { name: 'messages', type: 'array', description: 'Array of message objects, each with id and threadId.' },
        { name: 'nextPageToken', type: 'string', description: 'Token to retrieve the next page of results.' },
        { name: 'resultSizeEstimate', type: 'number', description: 'Estimated total number of results.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/messages', paramMapping: { q: 'query', maxResults: 'query', labelIds: 'query' } }),
      mockExecute: async (_args, ctx) => ({
        messages: fakeArray(ctx.seed, 3, (s) => ({ id: fakeId(s, 16), threadId: fakeId(deriveSeed(s, 't'), 16) })),
        nextPageToken: undefined,
        resultSizeEstimate: 3,
      }),
    },
    {
      actionId: 'get_message',
      name: 'Get message',
      description: 'Get a single email message by its ID. Returns full content, metadata, or headers.',
      intents: [
        'read an email',
        'open an email',
        'see the content of this email',
        'read the full message',
        'what does this email say',
        'get a gmail message by id',
        'fetch a single email by id',
        'retrieve an email by its id',
        'get email metadata',
        'get message details',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Message ID.',
        },
        {
          name: 'format',
          type: 'string',
          required: false,
          description: 'Format: "full", "metadata", or "minimal".',
          default: 'full',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The message ID.' },
        { name: 'threadId', type: 'string', description: 'The thread this message belongs to.' },
        { name: 'snippet', type: 'string', description: 'Short plain-text preview of the message body.' },
        { name: 'labelIds', type: 'array', description: 'Labels applied to this message (e.g. INBOX, UNREAD).' },
        { name: 'payload', type: 'object', description: 'Full message payload including headers (From, To, Subject, Date) and body parts.' },
        { name: 'internalDate', type: 'string', description: 'Internal message date as milliseconds since epoch.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/messages/{id}', paramMapping: { id: 'path', format: 'query' } }),
      mockExecute: async (args, ctx) => {
        const id = String(args.id ?? fakeId(ctx.seed, 16))
        return {
          id,
          threadId: fakeId(deriveSeed(ctx.seed, 't'), 16),
          snippet: 'Mock email snippet for workflow authoring.',
          labelIds: ['INBOX'],
          payload: {
            headers: [
              { name: 'From', value: fakeEmail(deriveSeed(ctx.seed, 'from')) },
              { name: 'To', value: fakeEmail(deriveSeed(ctx.seed, 'to')) },
              { name: 'Subject', value: 'Mock Subject' },
              { name: 'Date', value: fakeIsoTimestamp(ctx.seed) },
            ],
            mimeType: 'text/plain',
            body: { data: '' },
          },
          internalDate: String(Date.parse(fakeIsoTimestamp(ctx.seed))),
        }
      },
    },
    {
      actionId: 'search_messages',
      name: 'Search messages',
      description: "Search across all your email using Gmail's search syntax (e.g., from:boss@company.com, subject:invoice, has:attachment).",
      intents: [
        'find emails from someone',
        'search my inbox for',
        'find emails about',
        'look for messages from',
        'find all emails with an attachment',
        'search for unread emails from last week',
      ],
      inputFields: [
        {
          name: 'q',
          type: 'string',
          required: true,
          description: 'Gmail search query using Gmail search operators (https://developers.google.com/gmail/api/guides/filtering), e.g. "from:boss@company.com", "subject:invoice has:attachment", "newer_than:7d is:unread".',
        },
        {
          name: 'maxResults',
          type: 'number',
          required: false,
          description: 'Maximum number of results to return.',
          default: 10,
        },
      ],
      outputFields: [
        { name: 'messages', type: 'array', description: 'Array of message objects, each with id and threadId.' },
        { name: 'nextPageToken', type: 'string', description: 'Token to retrieve the next page of results.' },
        { name: 'resultSizeEstimate', type: 'number', description: 'Estimated total number of results.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/messages', paramMapping: { q: 'query', maxResults: 'query' } }),
      mockExecute: async (_args, ctx) => ({
        messages: fakeArray(ctx.seed, 2, (s) => ({ id: fakeId(s, 16), threadId: fakeId(deriveSeed(s, 't'), 16) })),
        nextPageToken: undefined,
        resultSizeEstimate: 2,
      }),
    },
    {
      actionId: 'send_message',
      name: 'Send email',
      description: 'Compose and send an email message.',
      intents: [
        'email someone',
        'write an email',
        'compose a message',
        'send a letter',
        'reach out via email',
        'shoot an email to',
        'send an email to',
      ],
      inputFields: [
        {
          name: 'raw',
          type: 'string',
          required: true,
          description: 'The email message to send.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The ID of the sent message.' },
        { name: 'threadId', type: 'string', description: 'The thread ID the sent message belongs to.' },
        { name: 'labelIds', type: 'array', description: 'Labels applied to the sent message (typically SENT).' },
      ],
      execute: rest({ method: 'POST', path: '/users/me/messages/send', paramMapping: { raw: 'body' } }),
      mockExecute: async (_args, ctx) => ({
        id: fakeId(ctx.seed, 16),
        threadId: fakeId(deriveSeed(ctx.seed, 't'), 16),
        labelIds: ['SENT'],
      }),
    },
    {
      actionId: 'modify_labels',
      name: 'Modify labels (mark as read, star, archive)',
      description: 'Add or remove labels on an email to mark it as read, star it, archive it, move it to a folder, and more.',
      intents: [
        'mark email as read',
        'archive an email',
        'star a message',
        'mark as unread',
        'move email to a label',
        'flag an email',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Message ID to modify.',
        },
        {
          name: 'addLabelIds',
          type: 'object',
          required: false,
          description: 'Array of label IDs to add, e.g. ["STARRED", "IMPORTANT"].',
        },
        {
          name: 'removeLabelIds',
          type: 'object',
          required: false,
          description: 'Array of label IDs to remove, e.g. ["UNREAD", "INBOX"].',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The ID of the modified message.' },
        { name: 'threadId', type: 'string', description: 'The thread this message belongs to.' },
        { name: 'labelIds', type: 'array', description: 'Updated list of labels on the message.' },
      ],
      execute: rest({ method: 'POST', path: '/users/me/messages/{id}/modify', paramMapping: { id: 'path', addLabelIds: 'body', removeLabelIds: 'body' } }),
    },
    {
      actionId: 'trash_message',
      name: 'Delete email (move to trash)',
      description: 'Delete an email by moving it to the trash.',
      intents: [
        'delete an email',
        'throw away a message',
        'remove an email',
        'discard this email',
        'move to trash',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Message ID to trash.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The ID of the trashed message.' },
        { name: 'threadId', type: 'string', description: 'The thread this message belongs to.' },
        { name: 'labelIds', type: 'array', description: 'Labels on the message after trashing (includes TRASH).' },
      ],
      execute: rest({ method: 'POST', path: '/users/me/messages/{id}/trash', paramMapping: { id: 'path' } }),
    },
    {
      actionId: 'untrash_message',
      name: 'Restore from trash',
      description: 'Recover a message that was moved to the trash.',
      intents: [
        'recover a deleted email',
        'restore an email from trash',
        'get back a deleted message',
        'undelete an email',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Message ID to restore.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The ID of the restored message.' },
        { name: 'threadId', type: 'string', description: 'The thread this message belongs to.' },
        { name: 'labelIds', type: 'array', description: 'Labels on the message after restoration.' },
      ],
      execute: rest({ method: 'POST', path: '/users/me/messages/{id}/untrash', paramMapping: { id: 'path' } }),
    },
    {
      actionId: 'batch_modify_messages',
      name: 'Batch modify messages',
      description: 'Add or remove labels on multiple messages at once.',
      intents: [
        'mark all these emails as read',
        'archive multiple emails at once',
        'bulk label emails',
        'mark all as read',
      ],
      inputFields: [
        {
          name: 'ids',
          type: 'object',
          required: true,
          description: 'Array of message IDs to modify.',
        },
        {
          name: 'addLabelIds',
          type: 'object',
          required: false,
          description: 'Array of label IDs to add to all specified messages.',
        },
        {
          name: 'removeLabelIds',
          type: 'object',
          required: false,
          description: 'Array of label IDs to remove from all specified messages.',
        },
      ],
      outputFields: [
        { name: 'ok', type: 'boolean', description: 'True if the batch operation succeeded (204 No Content response).' },
      ],
      execute: rest({ method: 'POST', path: '/users/me/messages/batchModify', paramMapping: { ids: 'body', addLabelIds: 'body', removeLabelIds: 'body' } }),
    },
    {
      actionId: 'get_attachment',
      name: 'Get attachment',
      description: 'Download the data of a file attached to an email.',
      intents: [
        'download an email attachment',
        'get the file from this email',
        'save the PDF from an email',
      ],
      inputFields: [
        {
          name: 'messageId',
          type: 'string',
          required: true,
          description: 'The ID of the message containing the attachment.',
        },
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'The attachment ID.',
        },
      ],
      outputFields: [
        { name: 'size', type: 'number', description: 'The size of the attachment data in bytes.' },
        { name: 'data', type: 'string', description: 'Base64url-encoded attachment data.' },
        { name: 'attachmentId', type: 'string', description: 'The ID of the attachment (same as the requested id).' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/messages/{messageId}/attachments/{id}', paramMapping: { messageId: 'path', id: 'path' } }),
    },
    // ── Labels ────────────────────────────────────────────────
    {
      actionId: 'list_labels',
      name: 'List labels',
      description: 'List all labels in the Gmail account, including system labels (INBOX, SPAM, TRASH, etc.) and custom labels.',
      intents: [
        'see my gmail labels',
        'what labels do I have',
        'list email folders',
        'show my gmail folders',
      ],
      inputFields: [],
      outputFields: [
        { name: 'labels', type: 'array', description: 'Array of label objects, each with id, name, and type.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/labels', paramMapping: {} }),
    },
    {
      actionId: 'get_label',
      name: 'Get label',
      description: 'Get details for a specific label, including unread message and thread counts.',
      intents: [
        'get label details',
        'look up a gmail label',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Label ID.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The label ID.' },
        { name: 'name', type: 'string', description: 'The display name of the label.' },
        { name: 'type', type: 'string', description: 'Label type: "system" or "user".' },
        { name: 'messagesUnread', type: 'number', description: 'Number of unread messages with this label.' },
        { name: 'threadsUnread', type: 'number', description: 'Number of unread threads with this label.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/labels/{id}', paramMapping: { id: 'path' } }),
    },
    {
      actionId: 'create_label',
      name: 'Create label',
      description: 'Create a new custom label to organize your email.',
      intents: [
        'make a new email label',
        'create an email folder',
        'add a gmail label',
        'set up a new email category',
      ],
      inputFields: [
        {
          name: 'name',
          type: 'string',
          required: true,
          description: 'Name for the new label.',
        },
        {
          name: 'labelListVisibility',
          type: 'string',
          required: false,
          description: 'Visibility in label list: "labelShow", "labelShowIfUnread", or "labelHide".',
        },
        {
          name: 'messageListVisibility',
          type: 'string',
          required: false,
          description: 'Visibility in message list: "show" or "hide".',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The ID of the newly created label.' },
        { name: 'name', type: 'string', description: 'The display name of the label.' },
        { name: 'type', type: 'string', description: 'Label type (always "user" for created labels).' },
      ],
      execute: rest({ method: 'POST', path: '/users/me/labels', paramMapping: { name: 'body', labelListVisibility: 'body', messageListVisibility: 'body' } }),
    },
    {
      actionId: 'update_label',
      name: 'Update label',
      description: 'Rename a custom label or change its visibility settings.',
      intents: [
        'rename a gmail label',
        'change a label name',
        'update email folder name',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Label ID to update.',
        },
        {
          name: 'name',
          type: 'string',
          required: false,
          description: 'New label name.',
        },
        {
          name: 'labelListVisibility',
          type: 'string',
          required: false,
          description: 'Visibility in label list: "labelShow", "labelShowIfUnread", or "labelHide".',
        },
        {
          name: 'messageListVisibility',
          type: 'string',
          required: false,
          description: 'Visibility in message list: "show" or "hide".',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The ID of the updated label.' },
        { name: 'name', type: 'string', description: 'The updated display name of the label.' },
        { name: 'type', type: 'string', description: 'Label type: "system" or "user".' },
      ],
      execute: rest({ method: 'PUT', path: '/users/me/labels/{id}', paramMapping: { id: 'path', name: 'body', labelListVisibility: 'body', messageListVisibility: 'body' } }),
    },
    {
      actionId: 'delete_label',
      name: 'Delete label',
      description: 'Permanently delete a custom label. System labels cannot be deleted.',
      intents: [
        'remove a gmail label',
        'delete an email folder',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Label ID to delete.',
        },
      ],
      outputFields: [
        { name: 'ok', type: 'boolean', description: 'True if the label was successfully deleted.' },
      ],
      execute: rest({ method: 'DELETE', path: '/users/me/labels/{id}', paramMapping: { id: 'path' } }),
    },
    // ── Threads ───────────────────────────────────────────────
    {
      actionId: 'list_threads',
      name: 'List threads',
      description: 'List email conversation threads. Each thread groups related messages together.',
      intents: [
        'see email conversations',
        'show email threads',
        'browse my email discussions',
        'list conversation threads',
      ],
      inputFields: [
        {
          name: 'q',
          type: 'string',
          required: false,
          description: 'Gmail search filter using Gmail search operators (https://developers.google.com/gmail/api/guides/filtering), e.g. "from:someone@example.com", "newer_than:7d".',
        },
        {
          name: 'maxResults',
          type: 'number',
          required: false,
          description: 'Maximum number of threads to return.',
          default: 20,
        },
        {
          name: 'labelIds',
          type: 'string',
          required: false,
          description: 'Label to filter by.',
        },
        {
          name: 'pageToken',
          type: 'string',
          required: false,
          description: 'Token for the next page of results.',
        },
      ],
      outputFields: [
        { name: 'threads', type: 'array', description: 'Array of thread objects, each with id, snippet, and historyId.' },
        { name: 'nextPageToken', type: 'string', description: 'Token to retrieve the next page of results.' },
        { name: 'resultSizeEstimate', type: 'number', description: 'Estimated total number of results.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/threads', paramMapping: { q: 'query', maxResults: 'query', labelIds: 'query', pageToken: 'query' } }),
      mockExecute: async (_args, ctx) => ({
        threads: fakeArray(ctx.seed, 3, (s) => ({ id: fakeId(s, 16), snippet: 'Mock thread snippet.', historyId: fakeId(deriveSeed(s, 'h'), 8) })),
        nextPageToken: undefined,
        resultSizeEstimate: 3,
      }),
    },
    {
      actionId: 'get_thread',
      name: 'Get thread',
      description: 'Get a full email conversation thread with all its messages.',
      intents: [
        'read a full email conversation',
        'see all emails in a thread',
        'get the full back-and-forth',
        'read an email chain',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Thread ID to retrieve.',
        },
        {
          name: 'format',
          type: 'string',
          required: false,
          description: 'Format for messages: "full", "metadata", or "minimal".',
          default: 'full',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The thread ID.' },
        { name: 'snippet', type: 'string', description: 'Short plain-text preview of the most recent message.' },
        { name: 'messages', type: 'array', description: 'Array of message objects in the thread.' },
        { name: 'historyId', type: 'string', description: 'The ID of the last history record for this thread.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/threads/{id}', paramMapping: { id: 'path', format: 'query' } }),
      mockExecute: async (args, ctx) => ({
        id: String(args.id ?? fakeId(ctx.seed, 16)),
        snippet: 'Mock thread preview.',
        historyId: fakeId(deriveSeed(ctx.seed, 'h'), 8),
        messages: fakeArray(ctx.seed, 2, (s) => ({ id: fakeId(s, 16), threadId: String(args.id ?? fakeId(ctx.seed, 16)), snippet: 'Message snippet.' })),
      }),
    },
    {
      actionId: 'modify_thread',
      name: 'Modify thread labels',
      description: 'Add or remove labels on an entire conversation thread.',
      intents: [
        'archive a whole conversation',
        'mark a thread as read',
        'label an email conversation',
        'star an email thread',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Thread ID to modify.',
        },
        {
          name: 'addLabelIds',
          type: 'object',
          required: false,
          description: 'Array of label IDs to add.',
        },
        {
          name: 'removeLabelIds',
          type: 'object',
          required: false,
          description: 'Array of label IDs to remove.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The thread ID.' },
        { name: 'snippet', type: 'string', description: 'Short plain-text preview of the most recent message.' },
        { name: 'messages', type: 'array', description: 'Array of message objects with updated label sets.' },
      ],
      execute: rest({ method: 'POST', path: '/users/me/threads/{id}/modify', paramMapping: { id: 'path', addLabelIds: 'body', removeLabelIds: 'body' } }),
    },
    {
      actionId: 'trash_thread',
      name: 'Trash thread',
      description: 'Move an entire conversation thread to the trash.',
      intents: [
        'delete a whole conversation',
        'trash an email thread',
        'remove an entire email chain',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Thread ID to trash.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The thread ID that was trashed.' },
        { name: 'snippet', type: 'string', description: 'Short plain-text preview of the most recent message.' },
        { name: 'messages', type: 'array', description: 'Array of message objects in the trashed thread.' },
      ],
      execute: rest({ method: 'POST', path: '/users/me/threads/{id}/trash', paramMapping: { id: 'path' } }),
    },
    // ── Drafts ────────────────────────────────────────────────
    {
      actionId: 'list_drafts',
      name: 'List drafts',
      description: 'List unsent draft emails saved in the account.',
      intents: [
        'see my email drafts',
        'what drafts do I have saved',
        'show unsent emails',
        'check my draft emails',
      ],
      inputFields: [
        {
          name: 'maxResults',
          type: 'number',
          required: false,
          description: 'Maximum number of drafts to return.',
          default: 10,
        },
        {
          name: 'q',
          type: 'string',
          required: false,
          description: 'Gmail search filter using Gmail search operators (https://developers.google.com/gmail/api/guides/filtering).',
        },
      ],
      outputFields: [
        { name: 'drafts', type: 'array', description: 'Array of draft objects, each with id and message (containing id and threadId).' },
        { name: 'nextPageToken', type: 'string', description: 'Token to retrieve the next page of results.' },
        { name: 'resultSizeEstimate', type: 'number', description: 'Estimated total number of drafts.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/drafts', paramMapping: { maxResults: 'query', q: 'query' } }),
    },
    {
      actionId: 'get_draft',
      name: 'Get draft',
      description: 'Read the content of a specific saved draft email.',
      intents: [
        'read a draft email',
        'open a saved draft',
        'see an unsent email',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Draft ID to retrieve.',
        },
        {
          name: 'format',
          type: 'string',
          required: false,
          description: 'Format: "full", "metadata", or "minimal".',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The draft ID.' },
        { name: 'message', type: 'object', description: 'The draft message object with id, threadId, snippet, labelIds, and payload.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/drafts/{id}', paramMapping: { id: 'path', format: 'query' } }),
    },
    {
      actionId: 'send_draft',
      name: 'Send draft',
      description: 'Send a previously saved draft email.',
      intents: [
        'send a saved draft',
        'send the draft email',
        'finish and send a draft',
      ],
      inputFields: [
        {
          name: 'id',
          type: 'string',
          required: true,
          description: 'Draft ID to send.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'The ID of the sent message.' },
        { name: 'threadId', type: 'string', description: 'The thread ID the sent message belongs to.' },
        { name: 'labelIds', type: 'array', description: 'Labels applied to the sent message (typically SENT).' },
      ],
      execute: rest({ method: 'POST', path: '/users/me/drafts/send', paramMapping: { id: 'body' } }),
    },
    // ── Profile & Settings ───────────────────────────────────
    {
      actionId: 'get_profile',
      name: 'Get profile',
      description: 'Get the Gmail account info: email address, total messages, and total threads.',
      intents: [
        'get my gmail account info',
        'what email is connected',
        'check my gmail address',
      ],
      inputFields: [],
      outputFields: [
        { name: 'emailAddress', type: 'string', description: 'The email address of the account.' },
        { name: 'messagesTotal', type: 'number', description: 'Total number of messages in the mailbox.' },
        { name: 'threadsTotal', type: 'number', description: 'Total number of threads in the mailbox.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/profile', paramMapping: {} }),
    },
    {
      actionId: 'get_vacation',
      name: 'Get vacation settings',
      description: 'Check whether the out-of-office auto-reply is active and see what it says.',
      intents: [
        'check my out of office',
        'is my vacation reply on',
        'see my auto-reply settings',
      ],
      inputFields: [],
      outputFields: [
        { name: 'enableAutoReply', type: 'boolean', description: 'Whether the auto-reply is currently enabled.' },
        { name: 'responseSubject', type: 'string', description: 'Subject line for the auto-reply.' },
        { name: 'responseBodyPlainText', type: 'string', description: 'Plain text body of the auto-reply.' },
        { name: 'startTime', type: 'string', description: 'Auto-reply start time in milliseconds since epoch.' },
        { name: 'endTime', type: 'string', description: 'Auto-reply end time in milliseconds since epoch.' },
      ],
      execute: rest({ method: 'GET', path: '/users/me/settings/vacation', paramMapping: {} }),
    },
    {
      actionId: 'update_vacation',
      name: 'Update vacation settings',
      description: 'Turn the out-of-office auto-reply on or off, and set the response message.',
      intents: [
        'turn on out of office',
        'set up auto-reply',
        'enable vacation responder',
        'set my away message',
        'turn off out of office',
      ],
      inputFields: [
        {
          name: 'enableAutoReply',
          type: 'boolean',
          required: true,
          description: 'Whether to enable the out-of-office auto-reply.',
        },
        {
          name: 'responseSubject',
          type: 'string',
          required: false,
          description: 'Subject line for the auto-reply.',
        },
        {
          name: 'responseBodyPlainText',
          type: 'string',
          required: false,
          description: 'Plain text body for the auto-reply.',
        },
        {
          name: 'responseBodyHtml',
          type: 'string',
          required: false,
          description: 'HTML body for the auto-reply.',
        },
        {
          name: 'restrictToContacts',
          type: 'boolean',
          required: false,
          description: 'Only send auto-reply to people in contacts.',
        },
        {
          name: 'restrictToDomain',
          type: 'boolean',
          required: false,
          description: 'Only send auto-reply to people in the same domain.',
        },
        {
          name: 'startTime',
          type: 'string',
          required: false,
          description: 'Start time in milliseconds since epoch.',
        },
        {
          name: 'endTime',
          type: 'string',
          required: false,
          description: 'End time in milliseconds since epoch.',
        },
      ],
      outputFields: [
        { name: 'enableAutoReply', type: 'boolean', description: 'Whether the auto-reply is now enabled.' },
        { name: 'responseSubject', type: 'string', description: 'Subject line for the auto-reply.' },
        { name: 'responseBodyPlainText', type: 'string', description: 'Plain text body of the auto-reply.' },
        { name: 'startTime', type: 'string', description: 'Auto-reply start time in milliseconds since epoch.' },
        { name: 'endTime', type: 'string', description: 'Auto-reply end time in milliseconds since epoch.' },
      ],
      execute: rest({
        method: 'PUT',
        path: '/users/me/settings/vacation',
        paramMapping: {
          enableAutoReply: 'body',
          responseSubject: 'body',
          responseBodyPlainText: 'body',
          responseBodyHtml: 'body',
          restrictToContacts: 'body',
          restrictToDomain: 'body',
          startTime: 'body',
          endTime: 'body',
        },
      }),
    },
  ],
})
